local o = vim.o
o.ar = true -- reload file changes (autoread)
o.bri = true -- keep visual indent on wrap
o.bs = 'indent,eol,start' -- allow backspace
o.cc = '80' -- set visual guide (colorcolumn)
o.cole = 2 -- conceal level
o.cot = 'menuone,noinsert,noselect' -- complete option
o.et = true -- <tab> expands to spaces
o.hid = true -- allow multiple unsaved buffers
o.hls = false -- no highlight after search
o.hlsearch = true -- highlight all search results
o.mouse = 'a' -- enable mouse
o.nu = true -- current line number
o.rnu = true -- relative line number
o.smc = 500 -- don't syntax highlight after 500 lines
o.smd = false -- don't show '-- insert --'
o.so = 8 -- num of lines to keep above/below cursor
o.sts = 4 -- spaces per tab
o.sw = 4 -- columns per shift
o.swf = false -- no swap file
o.tgc = true -- use 24-bit color
o.tm = 500 -- timeout in ms (e.g. for whichkey)
o.ts = 4 -- columns per tabstop
o.wrap = false -- no word wrap
