return {
    ui = {
        Conceal = '- - .',
        CursorLineNr = 'lightest darker b',
        Folded = 'orange dark .',
        LineNr = 'lighter black .',
        MatchParen = 'teal darker u',
        Noise = '@Delimiter',
        NonText = 'light . .',
        Normal = 'white darkest .',
        PMenu = 'white black .',
        Title = 'yellow . .',
        Underlined = 'yellow . u',
        VertSplit = 'light black .',
        Visual = '. gray .',
    },
    syntax = {
        Comment = 'dark . i',
        Constant = 'purple . .',
        Delimiter = 'light . .',
        Directory = 'yellow . .',
        Function = 'lime . .',
        Identifier = 'orange - -',
        Operator = 'pink . .',
        PreProc = 'pink . .',
        Special = 'purple . .',
        Statement = 'pink . -',
        StorageClass = 'pink . .',
        String = 'yellow . .',
        Type = 'sky . i',
    },
    indent = { IndentMarker = 'dark . .' }, -- for indent_blankline
    nvimtree = {
        NvimTreeFolderIcon = 'teal . .',
        NvimTreeIndentMarker = '@IndentMarker',
        NvimTreeRootFolder = 'orange . .',
    },
    treesitter = {
        TSConstBuiltin = 'sky . .',
        TSPunctBracket = '@Delimiter',
        TSField = '- - -',
        TSFuncBuiltin = '@TSConstBuiltin',
        TSKeywordFunction = 'sky . i',
        TSNamespace = '- . .',
        TSParameter = 'orange . .',
        TSProperty = '- . .',
        TSVariableBuiltin = '@TSConstBuiltin',
        TSConstructor = '@TSConstBuiltin',
    },
    -- #region languages
    css = {
        cssBraces = '@Delimiter',
        cssCustomProp = '@Normal',
        cssIdentifier = 'orange . i',
        cssPseudoClassId = 'sky . i',
        cssProp = '@Normal',
        cssClassName = 'lime . i',
        cssClassNameDot = '@Delimiter',
        cssImportant = 'pink . .',
    },
    sass = {
        sassVariableAssignment = '@Delimiter',
        sassFunctionName = '@Function',
        sassProperty = '@Delimiter',
        sassMixinName = '@TSFuncBuiltin',
    },
    html = {
        htmlTag = '@Delimiter',
        htmlEndTag = '@Delimiter',
    },
    markdown = {
        markdownBold = '. . b',
        markdownItalic = '. . i',
        markdownListMarker = '@Delimiter',
    },
    -- #endregion languages
}
