;; extends
("$" @markup.math (#set! conceal ""))
((ident) @markup.math (#eq? @markup.math "nothing") (#set! conceal "∅"))
((ident) @markup.math (#eq? @markup.math "in") (#set! conceal "∈"))
((ident) @markup.math (#eq? @markup.math "quad") (#set! conceal " "))

; ((call 
;   item: (ident) @constant (#eq? @constant "cal") 
;   (formula (letter) @markup.math (#eq? @markup.math "F"))
;   ) @conceal (#set! conceal "F"))

((ident) @markup.math (#eq? @markup.math "AA") (#set! conceal "𝔸"))
((ident) @markup.math (#eq? @markup.math "BB") (#set! conceal "𝔹"))
((ident) @markup.math (#eq? @markup.math "CC") (#set! conceal "ℂ"))
((ident) @markup.math (#eq? @markup.math "DD") (#set! conceal "𝔻"))
((ident) @markup.math (#eq? @markup.math "EE") (#set! conceal "𝔼"))
((ident) @markup.math (#eq? @markup.math "FF") (#set! conceal "𝔽"))
((ident) @markup.math (#eq? @markup.math "GG") (#set! conceal "𝔾"))
((ident) @markup.math (#eq? @markup.math "HH") (#set! conceal "ℍ"))
((ident) @markup.math (#eq? @markup.math "II") (#set! conceal "𝕀"))
((ident) @markup.math (#eq? @markup.math "JJ") (#set! conceal "𝕁"))
((ident) @markup.math (#eq? @markup.math "KK") (#set! conceal "𝕂"))
((ident) @markup.math (#eq? @markup.math "LL") (#set! conceal "𝕃"))
((ident) @markup.math (#eq? @markup.math "MM") (#set! conceal "𝕄"))
((ident) @markup.math (#eq? @markup.math "NN") (#set! conceal "ℕ"))
((ident) @markup.math (#eq? @markup.math "OO") (#set! conceal "𝕆"))
((ident) @markup.math (#eq? @markup.math "PP") (#set! conceal "ℙ"))
((ident) @markup.math (#eq? @markup.math "QQ") (#set! conceal "ℚ"))
((ident) @markup.math (#eq? @markup.math "RR") (#set! conceal "ℝ"))
((ident) @markup.math (#eq? @markup.math "SS") (#set! conceal "𝕊"))
((ident) @markup.math (#eq? @markup.math "TT") (#set! conceal "𝕋"))
((ident) @markup.math (#eq? @markup.math "UU") (#set! conceal "𝕌"))
((ident) @markup.math (#eq? @markup.math "VV") (#set! conceal "𝕍"))
((ident) @markup.math (#eq? @markup.math "WW") (#set! conceal "𝕎"))
((ident) @markup.math (#eq? @markup.math "XX") (#set! conceal "𝕏"))
((ident) @markup.math (#eq? @markup.math "YY") (#set! conceal "𝕐"))
((ident) @markup.math (#eq? @markup.math "ZZ") (#set! conceal "ℤ"))
