;; extends 

(("else" @conditional) (#set! conceal "e"))
(("yield" @keyword) (#set! conceal "Y"))
(("for" @repeat) (#set! conceal "F"))
(("global" @keyword) (#set! conceal "G"))
(("if" @conditional) (#set! conceal "?"))
(("not" @keyword.operator) (#set! conceal "!"))
(("or" @keyword.operator) (#set! conceal "|"))
((import_from_statement ("from") @include) (#set! conceal "f"))
(("return" @keyword) (#set! conceal "R"))
(("continue" @keyword) (#set! conceal "C"))
(("pass" @keyword) (#set! conceal "P"))
(("elif" @conditional) (#set! conceal "e"))
(("del" @keyword) (#set! conceal "D"))
(("lambda" @include) (#set! conceal "λ"))
((call function: (identifier) @function.builtin (#eq? @function.builtin "print")) (#set! conceal "p"))
(("class" @keyword) (#set! conceal "c"))
(("assert" @keyword) (#set! conceal "?"))
((yield ("from") @keyword) (#set! conceal "F"))
(("and" @keyword.operator) (#set! conceal "&"))
(("with" @keyword) (#set! conceal "w"))
(("import" @include) (#set! conceal "i"))
(("def" @keyword.function) (#set! conceal "f"))
(("break" @keyword) (#set! conceal "B"))
(("while" @repeat) (#set! conceal "W"))
